apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
data:
  config: |
    tcp-keepalive 240
    maxmemory 1mb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: data-tier
  name: data-tier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-tier
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: data-tier
    spec:
      volumes:
      - name: config
        configMap:
          name: redis-config
          items:
          - key: config
            path: redis.conf
      containers:
      - image: redis
        name: redis
        command:
        - redis-server
        - /etc/redis/redis.conf
        ports:
        - containerPort: 6379
        resources: {}
        volumeMounts:
        - mountPath: /etc/redis
          name: config
status: {}
