apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-gateway
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: gateway
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: gateway
    spec:
      containers:
        - image: haproxy:2.4
          imagePullPolicy: IfNotPresent
          name: ambassdor
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /usr/local/etc/haproxy
              name: config-volume
        - command:
            - sh
            - -c
            - while true; do curl localhost:9090; sleep 5; done
          image: radial/busyboxplus:curl
          imagePullPolicy: IfNotPresent
          name: busybox
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      initContainers:
        - command:
            - sh
            - -c
            - sleep 10
          image: busybox:stable
          imagePullPolicy: IfNotPresent
          name: sidecar
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - configMap:
            defaultMode: 420
            name: haproxy-config
          name: config-volume
