apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-frontend
  namespace: hive
spec:
  replicas: 5
  selector:
    matchLabels:
      app: web-frontend
  template:
    metadata:
      labels:
        app: web-frontend
    spec:
      containers:
        - image: nginx:1.14.2
          name: nginx
          resources: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: internal-api-blue
  namespace: hive
spec:
  replicas: 1
  selector:
    matchLabels:
      app: internal-api
      color: blue
  template:
    metadata:
      labels:
        app: internal-api
        color: blue
    spec:
      containers:
        - name: nginx
          image: linuxacademycontent/ckad-nginx:blue
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: api-svc
  namespace: hive
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: internal-api
    color: blue
  type: ClusterIP
