apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |-
    server {
        listen 80;
        server_name localhost;

        location / {
        proxy_pass http://localhost:5000/;
        proxy_set_header Host "localhost";
        }
    }
