apiVersion: apps/v1
kind: Deployment
metadata:
  name: bruce
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bruce
  template:
    metadata:
      labels:
        app: bruce
    spec:
      containers:
        - image: ninx:stable
          name: nginx
          ports:
            - containerPort: 80
              protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bat
  namespace: cave
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bat
  template:
    metadata:
      labels:
        app: bat
    spec:
      containers:
        - command:
            - sh
            - -c
            - kubectl get pods; while true; do sleep 3600; done
          image: wernight/kubectl
          imagePullPolicy: Always
          name: kubectl
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gotham-sa
  namespace: cave
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: robin-rb
  namespace: cave
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: robin-role
subjects:
  - kind: ServiceAccount
    name: gotham-sa
    namespace: cave
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: robin-role
  namespace: cave
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
