apiVersion: apps/v1
kind: Deployment
metadata:
  name: fish
spec:
  replicas: 5
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: fish
  strategy:
    rollingUpdate:
      maxSurge: 10%
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: fish
    spec:
      containers:
        - image: nginx:1.20.2
          imagePullPolicy: IfNotPresent
          name: nginx
          ports:
            - containerPort: 80
              protocol: TCP
