apiVersion: v1
kind: Pod
metadata:
  name: client
spec:
  containers:
    - name: main
      image: radial/busyboxplus:curl
      command:
        ["sh", "-c", "while true; do curl -m 3 api-svc:7171; sleep 5; done"]
---
apiVersion: v1
kind: Service
metadata:
  name: api-svc
spec:
  ports:
    - port: 7171
      protocol: TCP
      targetPort: 80
  selector:
    app: api
  sessionAffinity: None
  type: ClusterIP
