apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv
  labels:
    type: local
spec:
  storageClassName: host
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc
spec:
  storageClassName: host
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: persist
spec:
  volumes:
    - name: pvc-volume
      persistentVolumeClaim:
        claimName: pvc
  containers:
    - name: task-pv-container
      image: redis
      volumeMounts:
        - mountPath: "/data"
          name: pvc-volume
