apiVersion: v1
data:
  tkn: aHk4c3pLMml1
kind: Secret
metadata:
  creationTimestamp: null
  name: xh8jqk7z
---
apiVersion: v1
kind: Pod
metadata:
  name: server
spec:
  containers:
  - name: container
    image: httpd:2.4.39-alpine
    env:
    - name: SECRET_TKN
      valueFrom:
        secretKeyRef:
          name: xh8jqk7z
          key: tkn
