apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: webserver
  name: mypod
spec:
  containers:
  - image: nginx:latest
    name: mypod
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
