apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: data-tier
  name: data-tier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-tier
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: data-tier
    spec:
      containers:
      - image: redis
        name: redis
        ports:
        - containerPort: 6379
        resources: {}
status: {}
