apiVersion: v1
kind: Secret
metadata:
  name: app-tier-secret
stringData:
  api-key: LRcAmM1904ywzK3esX
  decoded: hello
data:
  encoded: aGVsbG8=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: microservice
    tier: app
  name: app-tier
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: app
  strategy: {}
  template:
    metadata:
      labels:
        tier: app
    spec:
      containers:
        - image: lrakai/microservices:server-v1
          name: webserver
          env:
            - name: REDIS_URL
              value: redis://data-tier:6379
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: app-tier-secret
                  key: api-key
          ports:
            - containerPort: 8080
          resources: {}
status: {}
