apiVersion: v1
kind: Secret
metadata:
  name: app-secret
data:
  secret: cGFzc3dvcmQ=
---
apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
spec:
  volumes:
  - name: secret-vol
    secret:
      secretName: app-secret
  containers:
  - image: busybox
    name: secret-container
    command: ["sleep", "3600"]
    env:
    - name: secret-env
      valueFrom:
        secretKeyRef:
          name: app-secret
          key: secret
    envFrom:
    - secretRef:
        name: app-secret
    volumeMounts:
    - name: secret-vol
      mountPath: /tmp
