apiVersion: v1
kind: Pod
metadata:
  labels:
    run: sidecar
  name: sidecar
spec:
  volumes:
    - name: sidecar-storage
      emptyDir: {}
  containers:
    - image: busybox
      name: main
      command:
        - sh
        - -c
        - 'i=1; while true; do echo "run $i" >> /tmp/log.log; i=$((i+1)); sleep 2; done'
      volumeMounts:
        - name: sidecar-storage
          mountPath: /tmp
    - image: busybox
      name: sidecar
      command:
        - sh
        - -c
        - "while true; do tail /tmp/log.log -n 1; sleep 2; done"
      volumeMounts:
        - name: sidecar-storage
          mountPath: /tmp
